Repository AY2324S1-CS2113-F11-2/tp, pull requests merged in 2023-10, with the labels that each got.

#19 Add Ingredient and IngredientList class
  src/main/java/essenmakanan/ingredient/Ingredient.java
  src/main/java/essenmakanan/ingredient/IngredientList.java
Labels: priority.High

#21 Add exception and IngredientListTest
  src/main/java/essenmakanan/exception/EssenMakananException.java
  src/main/java/essenmakanan/ingredient/IngredientList.java
  src/test/java/essenmakanan/IngredientListTest.java
Labels: priority.Medium

#46 Make code more defensive and increase SRP of UI
  src/main/java/essenmakanan/parser/IngredientParser.java
  src/main/java/essenmakanan/parser/RecipeParser.java
  src/main/java/essenmakanan/ui/Ui.java
Labels: type.Task, type.Test

#59 Parser integration and enhancement of Ingredient class
  src/main/java/essenmakanan/EssenMakanan.java
  src/main/java/essenmakanan/command/AddIngredientCommand.java
  src/main/java/essenmakanan/command/AddRecipeCommand.java
  src/main/java/essenmakanan/command/ViewIngredientsCommand.java
  src/main/java/essenmakanan/exception/EssenMakananException.java
  src/main/java/essenmakanan/ingredient/Ingredient.java
  src/main/java/essenmakanan/ingredient/IngredientList.java
  src/main/java/essenmakanan/ingredient/IngredientUnit.java
  src/main/java/essenmakanan/parser/IngredientParser.java
  src/main/java/essenmakanan/recipe/Step.java
  src/main/java/essenmakanan/recipe/Tag.java
  src/main/java/essenmakanan/ui/Ui.java
  src/test/java/essenmakanan/IngredientListTest.java
  src/test/java/essenmakanan/parser/IngredientParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#67 Junit tests and exceptions for editing ingredients
  src/main/java/essenmakanan/command/EditIngredientCommand.java
  src/main/java/essenmakanan/ingredient/IngredientList.java
  src/test/java/essenmakanan/ingredient/EditIngredientTest.java
  src/test/java/essenmakanan/ingredient/IngredientListTest.java
Labels: type.Test

#76 Update developer guide for viewing ingredients
  docs/DeveloperGuide.md
  docs/diagrams/AddNewRecipeSequenceDiagram.puml
  docs/diagrams/HelpFunctionSequenceDiagram.puml
  docs/diagrams/Style.puml
  docs/diagrams/ViewAllIngredientSequenceDiagram.puml
  docs/images/HelpFunctionSequenceDiagram.png
  docs/images/ViewAllIngredientSequenceDiagram.png
Labels: type.Documentation

#77 Add sequence diagram for viewing all recipes and updating DG
  docs/DeveloperGuide.md
  docs/diagrams/ViewAllRecipeSequenceDiagram.puml
  docs/images/ViewAllRecipeSequenceDiagram.png
Labels: type.Documentation

#79 Improve view ingredients documentation
  docs/DeveloperGuide.md
Labels: type.Documentation

#96 Add ingredient list into all recipes
  src/main/java/essenmakanan/command/AddIngredientCommand.java
  src/main/java/essenmakanan/command/AddRecipeCommand.java
  src/main/java/essenmakanan/parser/IngredientParser.java
  src/main/java/essenmakanan/recipe/Recipe.java
  src/main/java/essenmakanan/recipe/RecipeIngredientList.java
  src/main/java/essenmakanan/recipe/RecipeList.java
  src/main/java/essenmakanan/recipe/RecipeStepList.java
  src/main/java/essenmakanan/ui/Ui.java
  src/test/java/essenmakanan/parser/AddRecipeCommandTest.java
  src/test/java/essenmakanan/parser/IngredientParserTest.java
  src/test/java/essenmakanan/recipe/AddRecipeTest.java
Labels: type.Enhancement

#102 View and filter functions for ingredients
  src/main/java/essenmakanan/command/EditIngredientCommand.java
  src/main/java/essenmakanan/command/EditRecipeCommand.java
  src/main/java/essenmakanan/command/FilterRecipesCommand.java
  src/main/java/essenmakanan/command/StartRecipeCommand.java
  src/main/java/essenmakanan/command/ViewSpecificIngredientCommand.java
  src/main/java/essenmakanan/ingredient/IngredientList.java
  src/main/java/essenmakanan/parser/IngredientParser.java
  src/main/java/essenmakanan/parser/Parser.java
  src/main/java/essenmakanan/parser/RecipeParser.java
  src/main/java/essenmakanan/recipe/RecipeIngredientList.java
  src/main/java/essenmakanan/recipe/RecipeList.java
  src/main/java/essenmakanan/ui/Ui.java
  src/test/java/essenmakanan/command/DeleteIngredientCommandTest.java
  src/test/java/essenmakanan/command/DeleteRecipeCommandTest.java
  src/test/java/essenmakanan/ingredient/IngredientListTest.java
  src/test/java/essenmakanan/ingredient/IngredientTest.java
  src/test/java/essenmakanan/parser/AddRecipeCommandTest.java
  src/test/java/essenmakanan/recipe/AddRecipeTest.java
Labels: type.Story
