Repository AY2324S1-CS2113-F11-2/tp, pull requests merged in 2023-11, with the labels that each got.

#111 Fix bug that does not allow for steps with multiple words
  data/ingredients.txt
  data/recipes.txt
  src/main/java/essenmakanan/command/AddRecipeCommand.java
Labels: type.Bug, priority.High

#114 Fix bug where empty steps are not caught
  src/main/java/essenmakanan/command/AddRecipeCommand.java
  src/main/java/essenmakanan/recipe/RecipeList.java
Labels: type.Bug

#115 Fix add recipe with tag bug
  src/main/java/essenmakanan/command/AddRecipeCommand.java
Labels: type.Bug, priority.High

#120 Documentation on edit recipe and reformating
  docs/UserGuide.md
  docs/add_recipe_eg_1.png.png
  docs/add_recipe_eg_2.png
  docs/edit_recipe_eg_1.png
  docs/edit_recipe_eg_2.png.png
Labels: type.Documentation

#118 Update help function and print statements
  src/main/java/essenmakanan/exception/EssenOutOfRangeException.java
  src/main/java/essenmakanan/parser/IngredientParser.java
  src/main/java/essenmakanan/parser/RecipeParser.java
  src/main/java/essenmakanan/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#121 [Documentation] Added links to various sections
  docs/UserGuide.md
Labels: type.Documentation

#122 [Test] Add tests to check for empty steps and jumbled order of tags
  src/main/java/essenmakanan/command/AddRecipeCommand.java
  src/test/java/essenmakanan/parser/AddRecipeCommandTest.java
  src/test/java/essenmakanan/recipe/AddRecipeTest.java
Labels: type.Test

#213 Add recipe now only uses 1 integrated method. Tags working
  src/main/java/essenmakanan/command/AddRecipeCommand.java
  src/main/java/essenmakanan/parser/Parser.java
  src/main/java/essenmakanan/recipe/Recipe.java
  src/main/java/essenmakanan/recipe/RecipeStepList.java
  src/main/java/essenmakanan/recipe/Tag.java
  src/main/java/essenmakanan/ui/Ui.java
  src/test/java/essenmakanan/parser/AddRecipeCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement

#226 Changed ingredient unit from string to double
  src/main/java/essenmakanan/command/StartRecipeCommand.java
  src/main/java/essenmakanan/ingredient/Ingredient.java
  src/main/java/essenmakanan/ingredient/IngredientList.java
  src/main/java/essenmakanan/parser/IngredientParser.java
  src/main/java/essenmakanan/parser/RecipeParser.java
  src/main/java/essenmakanan/storage/IngredientStorage.java
  src/main/java/essenmakanan/ui/Ui.java
  src/test/java/essenmakanan/command/DeleteIngredientCommandTest.java
  src/test/java/essenmakanan/command/StartRecipeCommandTest.java
  src/test/java/essenmakanan/ingredient/EditIngredientTest.java
  src/test/java/essenmakanan/ingredient/IngredientListTest.java
  src/test/java/essenmakanan/ingredient/IngredientTest.java
  src/test/java/essenmakanan/parser/AddRecipeCommandTest.java
  src/test/java/essenmakanan/parser/IngredientParserTest.java
  src/test/java/essenmakanan/recipe/AddRecipeTest.java
  src/test/java/essenmakanan/storage/StorageTest.java
Labels: type.Enhancement

#227 Plan feature
  src/main/java/essenmakanan/command/PlanCommand.java
  src/main/java/essenmakanan/command/StartRecipeCommand.java
  src/main/java/essenmakanan/parser/IngredientParser.java
  src/main/java/essenmakanan/parser/Parser.java
  src/main/java/essenmakanan/parser/RecipeParser.java
  src/main/java/essenmakanan/ui/Ui.java
Labels: type.Story

#228 No more duplicate ingredients
  src/main/java/essenmakanan/command/AddIngredientCommand.java
  src/main/java/essenmakanan/ingredient/Ingredient.java
  src/main/java/essenmakanan/ingredient/IngredientList.java
  src/main/java/essenmakanan/parser/IngredientParser.java
  src/main/java/essenmakanan/parser/Parser.java
  src/main/java/essenmakanan/ui/Ui.java
Labels: type.Enhancement

#235 Implemented duration for steps
  src/main/java/essenmakanan/command/AddRecipeCommand.java
  src/main/java/essenmakanan/parser/RecipeParser.java
  src/main/java/essenmakanan/recipe/RecipeStepList.java
  src/test/java/essenmakanan/parser/AddRecipeCommandTest.java
Labels: type.Enhancement

#239 Handle invalid ingredient adding, use ingredient command
  src/main/java/essenmakanan/command/AddIngredientCommand.java
  src/main/java/essenmakanan/command/UseIngredientCommand.java
  src/main/java/essenmakanan/parser/IngredientParser.java
  src/main/java/essenmakanan/parser/Parser.java
  src/main/java/essenmakanan/ui/Ui.java
  src/test/java/essenmakanan/command/AddIngredientCommandTest.java
  src/test/java/essenmakanan/ingredient/UseIngredientTest.java
  src/test/java/essenmakanan/parser/IngredientParserTest.java
Labels: type.Bug
